version: '2'
services:

  redis:
    image: redis:latest
    restart: always

  ethereum_node:
    image: ethereum/client-go:stable
    restart: always
    entrypoint: geth --rpc --rpcaddr 0.0.0.0 --rpcapi eth,personal
    volumes:
      - "~/.ethereum:/root/.ethereum"         # blockchain client data directory


  ethereum-ganache-node:
    image: trufflesuite/ganache-cli
    restart: always
    ports:
      - 8545:8545

  minter-service:
    build:
      context: .
    command: wsgi_app.py
    depends_on:
      - redis
      - ethereum_node
    ports:
      - "8000:8000"                           # minter-service port (change first digit)
    volumes:
      - "/data:/app/data"                     # minter-service data directory
      - "${PWD}/conf/minter.conf:/app/conf/minter.conf"  # config file

  ico-info-service:
    build:
      context: .
    command: wsgi_ico_info.py
    depends_on:
      - ethereum_node
    ports:
      - "8001:8000"
    volumes:
      - "${PWD}/conf/ico_info.conf:/app/conf/ico_info.conf"


  
