version: '2'
services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  ethereum_node:
    image: ethereum/client-go:stable
    restart: always
    command: geth --rpcapi eth,personal
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - "$ETHEREUM_DATA:/root/.ethereum"

  minter-service:
    build:
      context: .
    depends_on:
      - redis
      - ethereum_node
    ports:
      - "8000:8000"
    volumes:
      - "$MINTER_DATA:/app/data"
      - "$MINTER_CONF:/app/conf/minter.conf"


